// try {
//     // let a = 0;
//     console.log(program);
// } catch (error) {
//     console.log("This is an error");
//     console.log(p);
// }
// finally{
//     console.log("I am a good boy");
// }


// const f = () =>{
//     try {
//         let a = 0;
//         console.log("program");
//         return;
//     } catch (error) {
//         console.log("This is an error");
//         console.log(p);
//     }
//     finally{
//         console.log("I am a good boy");
//     }
// }
// f();







const f = () =>{
    try {
        let a = 0;
        console.log("program");
        return;
    } catch (error) {
        console.log("This is an error");
        console.log(p);
    }
    finally{
        console.log("I am a good boy");
    }
}
f();
console.log("end");
